USE [DSA_BIZ02]
GO
/*
DROP TABLE [dbo].[TYP_MIEJSCOWOŒCI]
DROP TABLE [dbo].[MIEJSCOWOŒÆ]
DROP TABLE [dbo].[STAN_CYWILNY]
DROP TABLE [dbo].[STATUS_ZAWODOWY]
DROP TABLE [dbo].[TYP_AKTYWNOŒCI]
GO
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TYP_MIEJSCOWOŒCI](
	[tmi_id] [int] NOT NULL,
	[tmi_nazwa] [nvarchar](30) NOT NULL,
 CONSTRAINT [TYP_MIEJSCOWOŒCI_PK] PRIMARY KEY NONCLUSTERED 
(
	[tmi_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[MIEJSCOWOŒÆ](
	[mi_id] [int] NOT NULL,
	[mi_nazwa] [nvarchar](50) NOT NULL,
	[mi_id_typ_miejscowoœci] [int] NOT NULL,
 CONSTRAINT [MIEJSCOWOŒÆ_PK] PRIMARY KEY NONCLUSTERED 
(
	[mi_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[STAN_CYWILNY](
	[sc_id] [int] NOT NULL,
	[sc_nazwa] [nvarchar](30) NOT NULL,
 CONSTRAINT [STAN_CYWILNY_PK] PRIMARY KEY NONCLUSTERED 
(
	[sc_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[STATUS_ZAWODOWY](
	[sz_id] [int] NOT NULL,
	[sz_nazwa] [nvarchar](30) NOT NULL,
 CONSTRAINT [STATUS_ZAWODOWY_PK] PRIMARY KEY NONCLUSTERED 
(
	[sz_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[TYP_AKTYWNOŒCI](
	[tak_id] [int] NOT NULL,
	[tak_nazwa] [nvarchar](30) NOT NULL,
    [tak_opis] [nvarchar](255) NULL,
 CONSTRAINT [TYP_AKTYWNOŒCI_PK] PRIMARY KEY NONCLUSTERED 
(
	[tak_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]



CREATE TABLE [dbo].[TYP_WYDATKU](
	[twy_id] [int] NOT NULL,
	[twy_nazwa] [nvarchar](30) NOT NULL,
 CONSTRAINT [TYP_WYDATKU_PK] PRIMARY KEY NONCLUSTERED 
(
	[twy_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO