USE [DWH_BIZ02]
GO

DELETE FROM dbo.dKategoriaAktywnosci;
GO

INSERT INTO dbo.[dKategoriaAktywnosci]([dKAk_id],[dKAk_nazwa],[dKAk_typ])
SELECT	2,	'sen',	5	UNION ALL
SELECT	3,	'drzemka',	5	UNION ALL
SELECT	4,	'praca charytatywna',	1	UNION ALL
SELECT	5,	'praca dorywcza',	1	UNION ALL
SELECT	6,	'umowa o pracê',	1	UNION ALL
SELECT	7,	'studia',	2	UNION ALL
SELECT	8,	'nauka w szkole podstawowej',	2	UNION ALL
SELECT	9,	'nauka w gimnazium',	2	UNION ALL
SELECT	11,	'nauka w liceum'	,2	UNION ALL
SELECT	12,	'nauka w technikum',	2	UNION ALL
SELECT	14,	'zawodówka'	,2	UNION ALL
SELECT	15,	'nauka jêzyków obcych'	,2	UNION ALL
SELECT	16,	'kursy'	,2	UNION ALL
SELECT	17,	'granie w gry komputerowe',	3	UNION ALL
SELECT	18,	'granie w gry planszowe'	,3	UNION ALL
SELECT	19,	'kino'	,3	UNION ALL
SELECT	20,	'teatr'	,3	UNION ALL
SELECT	21,	'le¿enie'	,4	UNION ALL
SELECT	22,	'spacer	',4	UNION ALL
SELECT	23,	'czytanie ksi¹¿ek',	4	UNION ALL
SELECT	24,	's³uchanie muzyki',	4	UNION ALL
SELECT	25,	'siedzenie',	4	UNION ALL
SELECT	27,	'czytanie mangi/ komiksów',	4	UNION ALL
SELECT	28,	'przegl¹danie Internetu',4	UNION ALL
SELECT	29,	'ogl¹danie filmów/seriali/anime	',3	UNION ALL
SELECT	30,	'ogl¹danie telewizji',3	UNION ALL
SELECT	31,	'sprz¹tanie',	6	UNION ALL
SELECT	32,	'higiena',	6	UNION ALL
SELECT	33, 'odkurzanie',6	UNION ALL
SELECT	34,	'gotowanie',6	UNION ALL
SELECT	35,	'jedzenie',6	UNION ALL
SELECT	36,	'l¹dowy',7	UNION ALL
SELECT	37,	'morski',7	UNION ALL
SELECT	38,	'lotniczy',7	UNION ALL
SELECT	39,	'pi³ka no¿na',8	UNION ALL
SELECT	40,	'bieganie',8	UNION ALL
SELECT	41,	'p³ywanie',8	UNION ALL
SELECT	42,	'nordic walking',8	UNION ALL
SELECT	43,	'je¿dzenie rowerem',	8	UNION ALL
SELECT	44,	'koszykówka',8	UNION ALL
SELECT	46,	'umowa zlecenie',1	UNION ALL
SELECT	47,	'umowa o dzie³o',1	UNION ALL
SELECT	48,	'uczenie siê',	6	UNION ALL
SELECT	49,	'joga',8	UNION ALL
SELECT	50,	'gimnastyka',8	UNION ALL
SELECT	51,	'areobik',8	UNION ALL
SELECT	52,	'zakupy	',6	

GO

USE [DSA_BIZ02]

DELETE FROM dbo.mapping WHERE map_dwh_name = 'DWH_BIZ02' AND map_dwh_table = 'dKategoriaAktywnosci';
GO

INSERT INTO [dbo].[mapping]([map_status],[map_dwh_name],[map_dwh_table],[map_dwh_key],[map_src_name],[map_src_table],[map_src_key])


SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',2,'Z02B1','KATEGORIA_AKTYWNOŒCI',2 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',3,'Z02B1','KATEGORIA_AKTYWNOŒCI',3 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',4,'Z02B1','KATEGORIA_AKTYWNOŒCI',4 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',5,'Z02B1','KATEGORIA_AKTYWNOŒCI',5 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',6,'Z02B1','KATEGORIA_AKTYWNOŒCI',6 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',7,'Z02B1','KATEGORIA_AKTYWNOŒCI',7 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',8,'Z02B1','KATEGORIA_AKTYWNOŒCI',8 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',9,'Z02B1','KATEGORIA_AKTYWNOŒCI',9 UNION ALL

SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',11,'Z02B1','KATEGORIA_AKTYWNOŒCI',11 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',12,'Z02B1','KATEGORIA_AKTYWNOŒCI',12 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',14,'Z02B1','KATEGORIA_AKTYWNOŒCI',14 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',15,'Z02B1','KATEGORIA_AKTYWNOŒCI',15 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',16,'Z02B1','KATEGORIA_AKTYWNOŒCI',16 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',17,'Z02B1','KATEGORIA_AKTYWNOŒCI',17 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',18,'Z02B1','KATEGORIA_AKTYWNOŒCI',18 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',19,'Z02B1','KATEGORIA_AKTYWNOŒCI',19 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',20,'Z02B1','KATEGORIA_AKTYWNOŒCI',20 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',21,'Z02B1','KATEGORIA_AKTYWNOŒCI',21 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',22,'Z02B1','KATEGORIA_AKTYWNOŒCI',22 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',23,'Z02B1','KATEGORIA_AKTYWNOŒCI',23 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',24,'Z02B1','KATEGORIA_AKTYWNOŒCI',24 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',25,'Z02B1','KATEGORIA_AKTYWNOŒCI',25 UNION ALL

SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',27,'Z02B1','KATEGORIA_AKTYWNOŒCI',27 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',28,'Z02B1','KATEGORIA_AKTYWNOŒCI',28 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',29,'Z02B1','KATEGORIA_AKTYWNOŒCI',29 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',30,'Z02B1','KATEGORIA_AKTYWNOŒCI',30 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',31,'Z02B1','KATEGORIA_AKTYWNOŒCI',31 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',32,'Z02B1','KATEGORIA_AKTYWNOŒCI',32 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',33,'Z02B1','KATEGORIA_AKTYWNOŒCI',33 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',34,'Z02B1','KATEGORIA_AKTYWNOŒCI',34 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',35,'Z02B1','KATEGORIA_AKTYWNOŒCI',35 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',36,'Z02B1','KATEGORIA_AKTYWNOŒCI',36 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',37,'Z02B1','KATEGORIA_AKTYWNOŒCI',37 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',38,'Z02B1','KATEGORIA_AKTYWNOŒCI',38 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',39,'Z02B1','KATEGORIA_AKTYWNOŒCI',39 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',40,'Z02B1','KATEGORIA_AKTYWNOŒCI',40 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',41,'Z02B1','KATEGORIA_AKTYWNOŒCI',41 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',42,'Z02B1','KATEGORIA_AKTYWNOŒCI',42 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',43,'Z02B1','KATEGORIA_AKTYWNOŒCI',43 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',44,'Z02B1','KATEGORIA_AKTYWNOŒCI',44 UNION ALL

SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',46,'Z02B1','KATEGORIA_AKTYWNOŒCI',46 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',47,'Z02B1','KATEGORIA_AKTYWNOŒCI',47 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',48,'Z02B1','KATEGORIA_AKTYWNOŒCI',48 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',49,'Z02B1','KATEGORIA_AKTYWNOŒCI',49 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',50,'Z02B1','KATEGORIA_AKTYWNOŒCI',50 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',51,'Z02B1','KATEGORIA_AKTYWNOŒCI',51 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',52,'Z02B1','KATEGORIA_AKTYWNOŒCI',52 UNION ALL

SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',2,'Z02B2','KATEGORIA_AKTYWNOŒCI',2 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',3,'Z02B2','KATEGORIA_AKTYWNOŒCI',3 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',4,'Z02B2','KATEGORIA_AKTYWNOŒCI',4 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',5,'Z02B2','KATEGORIA_AKTYWNOŒCI',5 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',6,'Z02B2','KATEGORIA_AKTYWNOŒCI',6 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',7,'Z02B2','KATEGORIA_AKTYWNOŒCI',7 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',8,'Z02B2','KATEGORIA_AKTYWNOŒCI',8 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',9,'Z02B2','KATEGORIA_AKTYWNOŒCI',9 UNION ALL

SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',11,'Z02B2','KATEGORIA_AKTYWNOŒCI',11 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',12,'Z02B2','KATEGORIA_AKTYWNOŒCI',12 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',14,'Z02B2','KATEGORIA_AKTYWNOŒCI',14 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',15,'Z02B2','KATEGORIA_AKTYWNOŒCI',15 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',16,'Z02B2','KATEGORIA_AKTYWNOŒCI',16 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',17,'Z02B2','KATEGORIA_AKTYWNOŒCI',17 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',18,'Z02B2','KATEGORIA_AKTYWNOŒCI',18 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',19,'Z02B2','KATEGORIA_AKTYWNOŒCI',19 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',20,'Z02B2','KATEGORIA_AKTYWNOŒCI',20 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',21,'Z02B2','KATEGORIA_AKTYWNOŒCI',21 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',22,'Z02B2','KATEGORIA_AKTYWNOŒCI',22 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',23,'Z02B2','KATEGORIA_AKTYWNOŒCI',23 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',24,'Z02B2','KATEGORIA_AKTYWNOŒCI',24 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',25,'Z02B2','KATEGORIA_AKTYWNOŒCI',25 UNION ALL

SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',27,'Z02B2','KATEGORIA_AKTYWNOŒCI',27 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',28,'Z02B2','KATEGORIA_AKTYWNOŒCI',28 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',29,'Z02B2','KATEGORIA_AKTYWNOŒCI',29 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',30,'Z02B2','KATEGORIA_AKTYWNOŒCI',30 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',31,'Z02B2','KATEGORIA_AKTYWNOŒCI',31 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',32,'Z02B2','KATEGORIA_AKTYWNOŒCI',32 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',33,'Z02B2','KATEGORIA_AKTYWNOŒCI',33 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',34,'Z02B2','KATEGORIA_AKTYWNOŒCI',34 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',35,'Z02B2','KATEGORIA_AKTYWNOŒCI',35 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',36,'Z02B2','KATEGORIA_AKTYWNOŒCI',36 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',37,'Z02B2','KATEGORIA_AKTYWNOŒCI',37 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',38,'Z02B2','KATEGORIA_AKTYWNOŒCI',38 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',39,'Z02B2','KATEGORIA_AKTYWNOŒCI',39 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',40,'Z02B2','KATEGORIA_AKTYWNOŒCI',40 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',41,'Z02B2','KATEGORIA_AKTYWNOŒCI',41 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',42,'Z02B2','KATEGORIA_AKTYWNOŒCI',42 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',43,'Z02B2','KATEGORIA_AKTYWNOŒCI',43 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',44,'Z02B2','KATEGORIA_AKTYWNOŒCI',44 UNION ALL

SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',46,'Z02B2','KATEGORIA_AKTYWNOŒCI',46 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',47,'Z02B2','KATEGORIA_AKTYWNOŒCI',47 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',48,'Z02B2','KATEGORIA_AKTYWNOŒCI',48 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',49,'Z02B2','KATEGORIA_AKTYWNOŒCI',49 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',50,'Z02B2','KATEGORIA_AKTYWNOŒCI',50 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',51,'Z02B2','KATEGORIA_AKTYWNOŒCI',51 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',52,'Z02B2','KATEGORIA_AKTYWNOŒCI',52 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',2,'Z02B3','KATEGORIA_AKTYWNOŒCI',2 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',3,'Z02B3','KATEGORIA_AKTYWNOŒCI',3 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',4,'Z02B3','KATEGORIA_AKTYWNOŒCI',4 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',5,'Z02B3','KATEGORIA_AKTYWNOŒCI',5 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',6,'Z02B3','KATEGORIA_AKTYWNOŒCI',6 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',7,'Z02B3','KATEGORIA_AKTYWNOŒCI',7 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',8,'Z02B3','KATEGORIA_AKTYWNOŒCI',8 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',9,'Z02B3','KATEGORIA_AKTYWNOŒCI',9 UNION ALL

SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',11,'Z02B3','KATEGORIA_AKTYWNOŒCI',11 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',12,'Z02B3','KATEGORIA_AKTYWNOŒCI',12 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',14,'Z02B3','KATEGORIA_AKTYWNOŒCI',14 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',15,'Z02B3','KATEGORIA_AKTYWNOŒCI',15 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',16,'Z02B3','KATEGORIA_AKTYWNOŒCI',16 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',17,'Z02B3','KATEGORIA_AKTYWNOŒCI',17 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',18,'Z02B3','KATEGORIA_AKTYWNOŒCI',18 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',19,'Z02B3','KATEGORIA_AKTYWNOŒCI',19 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',20,'Z02B3','KATEGORIA_AKTYWNOŒCI',20 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',21,'Z02B3','KATEGORIA_AKTYWNOŒCI',21 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',22,'Z02B3','KATEGORIA_AKTYWNOŒCI',22 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',23,'Z02B3','KATEGORIA_AKTYWNOŒCI',23 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',24,'Z02B3','KATEGORIA_AKTYWNOŒCI',24 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',25,'Z02B3','KATEGORIA_AKTYWNOŒCI',25 UNION ALL

SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',27,'Z02B3','KATEGORIA_AKTYWNOŒCI',27 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',28,'Z02B3','KATEGORIA_AKTYWNOŒCI',28 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',29,'Z02B3','KATEGORIA_AKTYWNOŒCI',29 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',30,'Z02B3','KATEGORIA_AKTYWNOŒCI',30 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',31,'Z02B3','KATEGORIA_AKTYWNOŒCI',31 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',32,'Z02B3','KATEGORIA_AKTYWNOŒCI',32 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',33,'Z02B3','KATEGORIA_AKTYWNOŒCI',33 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',34,'Z02B3','KATEGORIA_AKTYWNOŒCI',34 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',35,'Z02B3','KATEGORIA_AKTYWNOŒCI',35 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',36,'Z02B3','KATEGORIA_AKTYWNOŒCI',36 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',37,'Z02B3','KATEGORIA_AKTYWNOŒCI',37 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',38,'Z02B3','KATEGORIA_AKTYWNOŒCI',38 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',39,'Z02B3','KATEGORIA_AKTYWNOŒCI',39 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',40,'Z02B3','KATEGORIA_AKTYWNOŒCI',40 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',41,'Z02B3','KATEGORIA_AKTYWNOŒCI',41 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',42,'Z02B3','KATEGORIA_AKTYWNOŒCI',42 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',43,'Z02B3','KATEGORIA_AKTYWNOŒCI',43 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',44,'Z02B3','KATEGORIA_AKTYWNOŒCI',44 UNION ALL

SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',46,'Z02B3','KATEGORIA_AKTYWNOŒCI',46 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',47,'Z02B3','KATEGORIA_AKTYWNOŒCI',47 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',48,'Z02B3','KATEGORIA_AKTYWNOŒCI',48 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',49,'Z02B3','KATEGORIA_AKTYWNOŒCI',49 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',50,'Z02B3','KATEGORIA_AKTYWNOŒCI',50 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',51,'Z02B3','KATEGORIA_AKTYWNOŒCI',51 UNION ALL
SELECT 'OK','DWH_BIZ02','dKategoriaAktywnosci',52,'Z02B3','KATEGORIA_AKTYWNOŒCI',52 





GO